server:
  domainName: game-exchange-api
  port: 3000

database:
  name: game_exchange_db
  protocol: postgres
  user: arthur
  password: retroexchange
  host: game-exchange-db
  port: 5432
  hashingMethod: bcrypt

nginx:
  hostPort: 8080
